services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:16.0
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./src/odoo/addons:/mnt/extra-addons
      - ./local:/mnt/local-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --init base --dev all
    networks:
      - odoo-net

volumes:
  db-data:
  odoo-data:

networks:
  odoo-net:
