version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:16.0
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo                  # Persistent Odoo data
      - ./odoo.conf:/etc/odoo/odoo.conf          # Configuration file
      - ./src/odoo/addons:/mnt/extra-addons.     # Official + extra addons
      - ./local:/mnt/local-addons                # Local custom modules
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_MASTER_PASSWD=admin
    command: --init base --dev all
    networks:
      - odoo-net

volumes:
  db-data:     
  odoo-data:   

networks:
  odoo-net:   
